import QtQuick 2.12

Item
{
	property color windowBg: "#ffffff"
	property color windowFg: "#000000"
	property color windowBgOver: "#f1f1f1"
	property color windowBgRipple: "#e5e5e5"
	property color windowFgOver: windowFg
	property color windowSubTextFg: "#999999"
	property color windowSubTextFgOver: "#919191"
	property color windowBoldFg: "#222222"
	property color windowBoldFgOver: "#222222"
	property color windowBgActive: "#40a7e3"
	property color windowFgActive: "#ffffff"
	property color windowActiveTextFg: "#168acd"
	property color windowShadowFg: "#000000"
	property color windowShadowFgFallback: "#f1f1f1"
	property color shadowFg: "#00000018"
	property color slideFadeOutBg: "#0000003c"
	property color slideFadeOutShadowFg: windowShadowFg
	property color imageBg: "#000000"
	property color imageBgTransparent: "#ffffff"
	property color activeButtonBg: windowBgActive
	property color activeButtonBgOver: "#39a5db"
	property color activeButtonBgRipple: "#2095d0"
	property color activeButtonFg: windowFgActive
	property color activeButtonFgOver: activeButtonFg
	property color activeButtonSecondaryFg: "#cceeff"
	property color activeButtonSecondaryFgOver: activeButtonSecondaryFg
	property color activeLineFg: "#37a1de"
	property color activeLineFgError: "#e48383"
	property color lightButtonBg: windowBg
	property color lightButtonBgOver: "#e3f1fa"
	property color lightButtonBgRipple: "#c9e4f6"
	property color lightButtonFg: windowActiveTextFg
	property color lightButtonFgOver: lightButtonFg
	property color attentionButtonFg: "#d14e4e"
	property color attentionButtonFgOver: "#d14e4e"
	property color attentionButtonBgOver: "#fcdfde"
	property color attentionButtonBgRipple: "#f4c3c2"
	property color outlineButtonBg: windowBg
	property color outlineButtonBgOver: lightButtonBgOver
	property color outlineButtonOutlineFg: windowBgActive
	property color outlineButtonBgRipple: lightButtonBgRipple
	property color menuBg: windowBg
	property color menuBgOver: windowBgOver
	property color menuBgRipple: windowBgRipple
	property color menuIconFg: "#999999"
	property color menuIconFgOver: "#8a8a8a"
	property color menuSubmenuArrowFg: "#373737"
	property color menuFgDisabled: "#cccccc"
	property color menuSeparatorFg: "#f1f1f1"
	property color scrollBarBg: "#00000053"
	property color scrollBarBgOver: "#0000007a"
	property color scrollBg: "#00000000"
	property color scrollBgOver: "#0000001a"
	property color smallCloseIconFg: "#c7c7c7"
	property color smallCloseIconFgOver: "#a3a3a3"
	property color radialFg: windowFgActive
	property color radialBg: "#00000056"
	property color placeholderFg: windowSubTextFg
	property color placeholderFgActive: "#aaaaaa"
	property color inputBorderFg: "#e0e0e0"
	property color filterInputBorderFg: "#54c3f3"
	property color checkboxFg: "#b3b3b3"
	property color sliderBgInactive: "#e1eaef"
	property color sliderBgActive: windowBgActive
	property color tooltipBg: "#eef2f5"
	property color tooltipFg: "#5d6c80"
	property color tooltipBorderFg: "#c9d1db"
	property color titleBg: windowBgOver
	property color titleShadow: "#00000003"
	property color titleButtonFg: "#ababab"
	property color titleButtonBgOver: "#e5e5e5"
	property color titleButtonFgOver: "#9a9a9a"
	property color titleButtonCloseBgOver: "#e81123"
	property color titleButtonCloseFgOver: windowFgActive
	property color titleFgActive: "#3e3c3e"
	property color titleFg: "#acacac"
	property color trayCounterBg: "#f23c34"
	property color trayCounterBgMute: "#888888"
	property color trayCounterFg: "#ffffff"
	property color trayCounterBgMacInvert: "#ffffff"
	property color trayCounterFgMacInvert: "#ffffff01"
	property color layerBg: "#0000007f"
	property color cancelIconFg: menuIconFg
	property color cancelIconFgOver: menuIconFgOver
	property color boxBg: windowBg
	property color boxTextFg: windowFg
	property color boxTextFgGood: "#4ab44a"
	property color boxTextFgError: "#d84d4d"
	property color boxTitleFg: "#404040"
	property color boxSearchBg: boxBg
	property color boxSearchCancelIconFg: cancelIconFg
	property color boxSearchCancelIconFgOver: cancelIconFgOver
	property color boxTitleAdditionalFg: "#808080"
	property color boxTitleCloseFg: cancelIconFg
	property color boxTitleCloseFgOver: cancelIconFgOver
	property color membersAboutLimitFg: windowSubTextFgOver
	property color contactsBg: windowBg
	property color contactsBgOver: windowBgOver
	property color contactsNameFg: boxTextFg
	property color contactsStatusFg: windowSubTextFg
	property color contactsStatusFgOver: windowSubTextFgOver
	property color contactsStatusFgOnline: windowActiveTextFg
	property color photoCropFadeBg: layerBg
	property color photoCropPointFg: "#ffffff7f"
	property color introBg: windowBg
	property color introTitleFg: windowBoldFg
	property color introDescriptionFg: windowSubTextFg
	property color introErrorFg: windowSubTextFg
	property color introCoverTopBg: "#0f89d0"
	property color introCoverBottomBg: "#39b0f0"
	property color introCoverIconsFg: "#5ec6ff"
	property color introCoverPlaneTrace: "#5ec6ff69"
	property color introCoverPlaneInner: "#c6d8e8"
	property color introCoverPlaneOuter: "#a1bed4"
	property color introCoverPlaneTop: "#ffffff"
	property color dialogsMenuIconFg: menuIconFg
	property color dialogsMenuIconFgOver: menuIconFgOver
	property color dialogsBg: windowBg
	property color dialogsNameFg: windowBoldFg
	property color dialogsChatIconFg: dialogsNameFg
	property color dialogsDateFg: windowSubTextFg
	property color dialogsTextFg: windowSubTextFg
	property color dialogsTextFgService: windowActiveTextFg
	property color dialogsDraftFg: "#dd4b39"
	property color dialogsVerifiedIconBg: windowBgActive
	property color dialogsVerifiedIconFg: windowFgActive
	property color dialogsSendingIconFg: "#c1c1c1"
	property color dialogsSentIconFg: "#2ca6e8"
	property color dialogsUnreadBg: windowBgActive
	property color dialogsUnreadBgMuted: "#bbbbbb"
	property color dialogsUnreadFg: windowFgActive
	property color dialogsArchiveFg: "#525252"
	property color dialogsOnlineBadgeFg: "#4dc920"
	property color dialogsBgOver: windowBgOver
	property color dialogsNameFgOver: windowBoldFgOver
	property color dialogsChatIconFgOver: dialogsNameFgOver
	property color dialogsDateFgOver: windowSubTextFgOver
	property color dialogsTextFgOver: windowSubTextFgOver
	property color dialogsTextFgServiceOver: dialogsTextFgService
	property color dialogsDraftFgOver: dialogsDraftFg
	property color dialogsVerifiedIconBgOver: dialogsVerifiedIconBg
	property color dialogsVerifiedIconFgOver: dialogsVerifiedIconFg
	property color dialogsSendingIconFgOver: dialogsSendingIconFg
	property color dialogsSentIconFgOver: dialogsSentIconFg
	property color dialogsUnreadBgOver: dialogsUnreadBg
	property color dialogsUnreadBgMutedOver: dialogsUnreadBgMuted
	property color dialogsUnreadFgOver: dialogsUnreadFg
	property color dialogsArchiveFgOver: "#525252"
	property color dialogsBgActive: "#419fd9"
	property color dialogsNameFgActive: windowFgActive
	property color dialogsChatIconFgActive: dialogsNameFgActive
	property color dialogsDateFgActive: windowFgActive
	property color dialogsTextFgActive: windowFgActive
	property color dialogsTextFgServiceActive: dialogsTextFgActive
	property color dialogsDraftFgActive: "#c6e1f7"
	property color dialogsVerifiedIconBgActive: dialogsTextFgActive
	property color dialogsVerifiedIconFgActive: dialogsBgActive
	property color dialogsSendingIconFgActive: "#ffffff99"
	property color dialogsSentIconFgActive: dialogsTextFgActive
	property color dialogsUnreadBgActive: dialogsTextFgActive
	property color dialogsUnreadBgMutedActive: dialogsDraftFgActive
	property color dialogsUnreadFgActive: dialogsBgActive
	property color dialogsOnlineBadgeFgActive: "#ffffff"
	property color dialogsForwardBg: dialogsBgActive
	property color dialogsForwardFg: dialogsNameFgActive
	property color searchedBarBg: windowBgOver
	property color searchedBarBorder: shadowFg
	property color searchedBarFg: windowSubTextFgOver
	property color topBarBg: windowBg
	property color emojiPanBg: windowBg
	property color emojiPanCategories: "#f7f7f7"
	property color emojiPanHeaderFg: windowSubTextFg
	property color emojiPanHeaderBg: "#fffffff2"
	property color emojiIconFg: "#999999"
	property color stickerPanDeleteBg: "#000000cc"
	property color stickerPanDeleteFg: windowFgActive
	property color stickerPreviewBg: "#ffffffb0"
	property color historyTextInFg: windowFg
	property color historyTextOutFg: windowFg
	property color historyCaptionInFg: historyTextInFg
	property color historyCaptionOutFg: historyTextOutFg
	property color historyFileNameInFg: historyTextInFg
	property color historyFileNameOutFg: historyTextOutFg
	property color historyOutIconFg: "#059de8"
	property color historyOutIconFgSelected: "#149ce6"
	property color historyIconFgInverted: windowFgActive
	property color historySendingOutIconFg: "#9dc2d9"
	property color historySendingInIconFg: "#a0adb5"
	property color historySendingInvertedIconFg: "#ffffffc8"
	property color historySystemBg: "#89a0b47f"
	property color historySystemBgSelected: "#bbc8d4a2"
	property color historySystemFg: windowFgActive
	property color historyUnreadBarBg: "#fcfbfa"
	property color historyUnreadBarBorder: shadowFg
	property color historyUnreadBarFg: "#538bb4"
	property color historyForwardChooseBg: "#0000004c"
	property color historyForwardChooseFg: windowFgActive
	property color historyPeer1NameFg: "#c03d33"
	property color historyPeer1UserpicBg: "#e17076"
	property color historyPeer2NameFg: "#4fad2d"
	property color historyPeer2UserpicBg: "#7bc862"
	property color historyPeer3NameFg: "#d09306"
	property color historyPeer3UserpicBg: "#e5ca77"
	property color historyPeer4NameFg: windowActiveTextFg
	property color historyPeer4UserpicBg: "#65aadd"
	property color historyPeer5NameFg: "#8544d6"
	property color historyPeer5UserpicBg: "#a695e7"
	property color historyPeer6NameFg: "#cd4073"
	property color historyPeer6UserpicBg: "#ee7aae"
	property color historyPeer7NameFg: "#2996ad"
	property color historyPeer7UserpicBg: "#6ec9cb"
	property color historyPeer8NameFg: "#ce671b"
	property color historyPeer8UserpicBg: "#faa774"
	property color historyPeerUserpicFg: windowFgActive
	property color historyScrollBarBg: "#00000040"
	property color historyScrollBarBgOver: "#00000053"
	property color historyScrollBg: "#00000000"
	property color historyScrollBgOver: "#0000001a"
	property color msgInBg: windowBg
	property color msgInBgSelected: "#bbe1fc"
	property color msgOutBg: "#def1fd"
	property color msgOutBgSelected: "#bbe1fc"
	property color msgSelectOverlay: "#358cd44c"
	property color msgStickerOverlay: "#358cd47f"
	property color msgInServiceFg: windowActiveTextFg
	property color msgInServiceFgSelected: windowActiveTextFg
	property color msgOutServiceFg: windowActiveTextFg
	property color msgOutServiceFgSelected: windowActiveTextFg
	property color msgInShadow: "#748ea229"
	property color msgInShadowSelected: "#1d629730"
	property color msgOutShadow: "#0d5a911a"
	property color msgOutShadowSelected: "#2e74aa29"
	property color msgInDateFg: "#a0acb6"
	property color msgInDateFgSelected: "#6a9cc5"
	property color msgOutDateFg: "#86a8c2"
	property color msgOutDateFgSelected: "#6ca0c2"
	property color msgServiceFg: windowFgActive
	property color msgServiceBg: "#00518059"
	property color msgServiceBgSelected: "#62afdda2"
	property color msgInReplyBarColor: activeLineFg
	property color msgInReplyBarSelColor: activeLineFg
	property color msgOutReplyBarColor: historyOutIconFg
	property color msgOutReplyBarSelColor: historyOutIconFgSelected
	property color msgImgReplyBarColor: msgServiceFg
	property color msgInMonoFg: "#4e7391"
	property color msgOutMonoFg: "#4e7391"
	property color msgDateImgFg: msgServiceFg
	property color msgDateImgBg: "#00000054"
	property color msgDateImgBgOver: "#00000074"
	property color msgDateImgBgSelected: "#1c4a7187"
	property color msgFileThumbLinkInFg: "#168acd"
	property color msgFileThumbLinkInFgSelected: lightButtonFgOver
	property color msgFileThumbLinkOutFg: "#0a8bd0"
	property color msgFileThumbLinkOutFgSelected: lightButtonFgOver
	property color msgFileInBg: windowBgActive
	property color msgFileInBgOver: "#4eade3"
	property color msgFileInBgSelected: "#51a3d3"
	property color msgFileOutBg: windowBgActive
	property color msgFileOutBgOver: "#4eade3"
	property color msgFileOutBgSelected: "#51a3d3"
	property color msgFile1Bg: "#72b1df"
	property color msgFile1BgDark: "#5c9ece"
	property color msgFile1BgOver: "#5294c4"
	property color msgFile1BgSelected: "#5099d0"
	property color msgFile2Bg: "#61b96e"
	property color msgFile2BgDark: "#4da859"
	property color msgFile2BgOver: "#44a050"
	property color msgFile2BgSelected: "#46a07e"
	property color msgFile3Bg: "#e47272"
	property color msgFile3BgDark: "#cd5b5e"
	property color msgFile3BgOver: "#c35154"
	property color msgFile3BgSelected: "#9f6a82"
	property color msgFile4Bg: "#efc274"
	property color msgFile4BgDark: "#e6a561"
	property color msgFile4BgOver: "#dc9c5a"
	property color msgFile4BgSelected: "#b19d84"
	property color msgWaveformInActive: windowBgActive
	property color msgWaveformInActiveSelected: "#51a3d3"
	property color msgWaveformInInactive: "#d4dee6"
	property color msgWaveformInInactiveSelected: "#9cc1e1"
	property color msgWaveformOutActive: windowBgActive
	property color msgWaveformOutActiveSelected: "#51a3d3"
	property color msgWaveformOutInactive: "#b3d4e7"
	property color msgWaveformOutInactiveSelected: "#87bcdb"
	property color msgBotKbOverBgAdd: "#ffffff20"
	property color msgBotKbIconFg: msgServiceFg
	property color msgBotKbRippleBg: "#00000020"
	property color mediaInFg: msgInDateFg
	property color mediaInFgSelected: msgInDateFgSelected
	property color mediaOutFg: "#80a3bd"
	property color mediaOutFgSelected: "#5f8fb3"
	property color youtubePlayIconBg: "#e83131c8"
	property color youtubePlayIconFg: windowFgActive
	property color videoPlayIconBg: "#0000007f"
	property color videoPlayIconFg: "#ffffff"
	property color toastBg: "#000000b2"
	property color toastFg: windowFgActive
	property color reportSpamBg: emojiPanHeaderBg
	property color reportSpamFg: windowFg
	property color historyToDownShadow: "#00000040"
	property color historyComposeAreaBg: msgInBg
	property color historyComposeAreaFg: historyTextInFg
	property color historyComposeAreaFgService: msgInDateFg
	property color historyComposeIconFg: menuIconFg
	property color historyComposeIconFgOver: menuIconFgOver
	property color historySendIconFg: windowBgActive
	property color historySendIconFgOver: windowBgActive
	property color historyPinnedBg: historyComposeAreaBg
	property color historyReplyBg: historyComposeAreaBg
	property color historyReplyCancelFg: cancelIconFg
	property color historyReplyCancelFgOver: cancelIconFgOver
	property color historyComposeButtonBg: historyComposeAreaBg
	property color historyComposeButtonBgOver: windowBgOver
	property color historyComposeButtonBgRipple: windowBgRipple
	property color overviewCheckBg: "#00000040"
	property color overviewCheckFg: windowBg
	property color overviewCheckFgActive: windowBg
	property color overviewPhotoSelectOverlay: "#40ace333"
	property color profileStatusFgOver: "#7c99b2"
	property color notificationsBoxMonitorFg: windowFg
	property color notificationsBoxScreenBg: dialogsBgActive
	property color notificationSampleUserpicFg: windowBgActive
	property color notificationSampleCloseFg: "#d7d7d7"
	property color notificationSampleTextFg: "#d7d7d7"
	property color notificationSampleNameFg: "#939393"
	property color mainMenuBg: windowBg
	property color mainMenuCoverBg: dialogsBgActive
	property color mainMenuCoverFg: windowFgActive
	property color mediaPlayerBg: windowBg
	property color mediaPlayerActiveFg: windowBgActive
	property color mediaPlayerInactiveFg: sliderBgInactive
	property color mediaPlayerDisabledFg: "#9dd1ef"
	property color mediaviewFileBg: windowBg
	property color mediaviewFileNameFg: windowFg
	property color mediaviewFileSizeFg: windowSubTextFg
	property color mediaviewFileRedCornerFg: "#d55959"
	property color mediaviewFileYellowCornerFg: "#e8a659"
	property color mediaviewFileGreenCornerFg: "#49a957"
	property color mediaviewFileBlueCornerFg: "#599dcf"
	property color mediaviewFileExtFg: activeButtonFg
	property color mediaviewMenuBg: "#383838"
	property color mediaviewMenuBgOver: "#505050"
	property color mediaviewMenuBgRipple: "#676767"
	property color mediaviewMenuFg: windowFgActive
	property color mediaviewBg: "#222222eb"
	property color mediaviewVideoBg: imageBg
	property color mediaviewControlBg: "#0000003c"
	property color mediaviewControlFg: windowFgActive
	property color mediaviewCaptionBg: "#11111180"
	property color mediaviewCaptionFg: mediaviewControlFg
	property color mediaviewTextLinkFg: "#91d9ff"
	property color mediaviewSaveMsgBg: toastBg
	property color mediaviewSaveMsgFg: toastFg
	property color mediaviewPlaybackActive: "#c7c7c7"
	property color mediaviewPlaybackInactive: "#252525"
	property color mediaviewPlaybackActiveOver: "#ffffff"
	property color mediaviewPlaybackInactiveOver: "#474747"
	property color mediaviewPlaybackProgressFg: "#ffffffc7"
	property color mediaviewPlaybackIconFg: mediaviewPlaybackActive
	property color mediaviewPlaybackIconFgOver: mediaviewPlaybackActiveOver
	property color mediaviewTransparentBg: "#ffffff"
	property color mediaviewTransparentFg: "#cccccc"
	property color notificationBg: windowBg
}
