import QtQuick 2.12

Item
{
	property color windowBg: "#282e33"
	property color windowFg: "#f5f5f5"
	property color windowBgOver: "#313b43"
	property color windowBgRipple: "#3f4850"
	property color windowFgOver: "#e9ecf0"
	property color windowSubTextFg: "#82868a"
	property color windowSubTextFgOver: "#797b7f"
	property color windowBoldFg: "#e9e8e8"
	property color windowBoldFgOver: "#e9e9e9"
	property color windowBgActive: "#3fc1b0"
	property color windowFgActive: "#ffffff"
	property color windowActiveTextFg: "#4be1c3"
	property color windowShadowFg: "#000000"
	property color windowShadowFgFallback: windowBg
	property color shadowFg: "#00000018"
	property color slideFadeOutBg: "#0000003c"
	property color slideFadeOutShadowFg: windowShadowFg
	property color imageBg: "#000000"
	property color imageBgTransparent: "#ffffff"
	property color activeButtonBg: "#2da192"
	property color activeButtonBgOver: "#32a898"
	property color activeButtonBgRipple: "#42b8a8"
	property color activeButtonFg: "#ffffff"
	property color activeButtonFgOver: "#ffffff"
	property color activeButtonSecondaryFg: "#8ee4d9"
	property color activeButtonSecondaryFgOver: activeButtonSecondaryFg
	property color activeLineFg: "#3ee2cc"
	property color activeLineFgError: "#f57878"
	property color lightButtonBg: "#282e33"
	property color lightButtonBgOver: "#313b43"
	property color lightButtonBgRipple: "#3c474f"
	property color lightButtonFg: "#79e8da"
	property color lightButtonFgOver: lightButtonFg
	property color attentionButtonFg: "#f57474"
	property color attentionButtonFgOver: "#e76060"
	property color attentionButtonBgOver: "#613a3a64"
	property color attentionButtonBgRipple: "#f4c3c2"
	property color outlineButtonBg: windowBg
	property color outlineButtonBgOver: "#313b43"
	property color outlineButtonOutlineFg: "#29baa7"
	property color outlineButtonBgRipple: "#3c474f"
	property color menuBg: "#282e33"
	property color menuBgOver: "#ffffff"
	property color menuBgRipple: "#26292d"
	property color menuIconFg: "#808080"
	property color menuIconFgOver: "#dcdcdc"
	property color menuSubmenuArrowFg: "#757575"
	property color menuFgDisabled: "#737373"
	property color menuSeparatorFg: "#42484d"
	property color scrollBarBg: "#ffffff53"
	property color scrollBarBgOver: "#ffffff7a"
	property color scrollBg: "#ffffff1a"
	property color scrollBgOver: "#ffffff2c"
	property color smallCloseIconFg: "#6d6d6d"
	property color smallCloseIconFgOver: "#a3a3a3"
	property color radialFg: windowFgActive
	property color radialBg: "#00000056"
	property color placeholderFg: "#818991"
	property color placeholderFgActive: "#5d6165"
	property color inputBorderFg: "#6f6f6f"
	property color filterInputBorderFg: "#3d444b"
	property color filterInputInactiveBg: "#3d444b"
	property color checkboxFg: "#6c6c6c"
	property color sliderBgInactive: "#545454"
	property color sliderBgActive: windowBgActive
	property color tooltipBg: "#282e33"
	property color tooltipFg: "#9a9e9c"
	property color tooltipBorderFg: "#313b43"
	property color titleShadow: "#00000003"
	property color titleBg: "#3a4047"
	property color titleBgActive: titleBg
	property color titleButtonBg: titleBg
	property color titleButtonFg: "#8b9096"
	property color titleButtonBgOver: "#4c535b"
	property color titleButtonFgOver: "#e0e0e0"
	property color titleButtonBgActive: titleButtonBg
	property color titleButtonFgActive: titleButtonFg
	property color titleButtonBgActiveOver: titleButtonBgOver
	property color titleButtonFgActiveOver: titleButtonFgOver
	property color titleButtonCloseBg: titleButtonBg
	property color titleButtonCloseFg: titleButtonFg
	property color titleButtonCloseBgOver: "#e81123"
	property color titleButtonCloseFgOver: windowFgActive
	property color titleButtonCloseBgActive: titleButtonCloseBg
	property color titleButtonCloseFgActive: titleButtonCloseFg
	property color titleButtonCloseBgActiveOver: titleButtonCloseBgOver
	property color titleButtonCloseFgActiveOver: titleButtonCloseFgOver
	property color titleFg: "#666666"
	property color titleFgActive: "#808080"
	property color trayCounterBg: "#f23c34"
	property color trayCounterBgMute: "#888888"
	property color trayCounterFg: "#ffffff"
	property color trayCounterBgMacInvert: "#ffffff"
	property color trayCounterFgMacInvert: "#ffffff01"
	property color layerBg: "#0000007f"
	property color cancelIconFg: "#666666"
	property color cancelIconFgOver: "#dcdcdc"
	property color boxBg: windowBg
	property color boxTextFg: windowFg
	property color boxTextFgGood: "#56dbce"
	property color boxTextFgError: "#d84d4d"
	property color boxTitleFg: "#ebebeb"
	property color boxSearchBg: "#282e33"
	property color boxTitleAdditionalFg: "#808080"
	property color boxTitleCloseFg: cancelIconFg
	property color boxTitleCloseFgOver: cancelIconFgOver
	property color membersAboutLimitFg: "#5e6065"
	property color contactsBg: "#222528"
	property color contactsBgOver: "#282e33"
	property color contactsNameFg: boxTextFg
	property color contactsStatusFg: "#808080"
	property color contactsStatusFgOver: "#808080"
	property color contactsStatusFgOnline: "#55e1d3"
	property color photoCropFadeBg: layerBg
	property color photoCropPointFg: "#ffffff7f"
	property color callArrowFg: "#2bc7b8"
	property color callArrowMissedFg: "#dd5b4a"
	property color introBg: windowBg
	property color introTitleFg: "#eeeeee"
	property color introDescriptionFg: "#999999"
	property color introErrorFg: "#999999"
	property color introCoverTopBg: "#188173"
	property color introCoverBottomBg: "#188173"
	property color introCoverIconsFg: "#34a495"
	property color introCoverPlaneTrace: "#329d8f"
	property color introCoverPlaneInner: "#ced9e2"
	property color introCoverPlaneOuter: "#97a9b5"
	property color introCoverPlaneTop: "#ffffff"
	property color dialogsMenuIconFg: menuIconFg
	property color dialogsMenuIconFgOver: menuIconFgOver
	property color dialogsBg: windowBg
	property color dialogsNameFg: "#f5f5f5"
	property color dialogsChatIconFg: dialogsNameFg
	property color dialogsDateFg: "#6d727c"
	property color dialogsTextFg: "#8d939e"
	property color dialogsTextFgService: "#ebebeb"
	property color dialogsDraftFg: "#ec6657"
	property color dialogsVerifiedIconBg: "#53edde"
	property color dialogsVerifiedIconFg: "#282e33"
	property color dialogsSendingIconFg: "#727272"
	property color dialogsSentIconFg: "#20eeda"
	property color dialogsUnreadBg: "#05a091"
	property color dialogsUnreadBgMuted: "#495159"
	property color dialogsUnreadFg: "#ffffff"
	property color dialogsOnlineBadgeFg: "#0ae7d2"
	property color dialogsBgOver: "#353c43"
	property color dialogsNameFgOver: windowBoldFgOver
	property color dialogsChatIconFgOver: dialogsNameFgOver
	property color dialogsDateFgOver: "#6d727c"
	property color dialogsTextFgOver: "#a3a7ae"
	property color dialogsTextFgServiceOver: "#f0f0f0"
	property color dialogsDraftFgOver: dialogsDraftFg
	property color dialogsVerifiedIconBgOver: "#53edde"
	property color dialogsVerifiedIconFgOver: dialogsVerifiedIconFg
	property color dialogsSendingIconFgOver: dialogsSendingIconFg
	property color dialogsSentIconFgOver: "#41f0df"
	property color dialogsUnreadBgOver: "#009687"
	property color dialogsUnreadBgMutedOver: "#555e67"
	property color dialogsUnreadFgOver: dialogsUnreadFg
	property color dialogsBgActive: "#009687"
	property color dialogsNameFgActive: windowFgActive
	property color dialogsChatIconFgActive: dialogsNameFgActive
	property color dialogsDateFgActive: windowFgActive
	property color dialogsTextFgActive: windowFgActive
	property color dialogsTextFgServiceActive: dialogsTextFgActive
	property color dialogsDraftFgActive: "#c6f7f3"
	property color dialogsVerifiedIconBgActive: dialogsTextFgActive
	property color dialogsVerifiedIconFgActive: dialogsBgActive
	property color dialogsSendingIconFgActive: "#ffffff99"
	property color dialogsSentIconFgActive: dialogsTextFgActive
	property color dialogsUnreadBgActive: dialogsTextFgActive
	property color dialogsUnreadBgMutedActive: "#cbf7e9"
	property color dialogsUnreadFgActive: "#039d8e"
	property color dialogsOnlineBadgeFgActive: "#ffffff"
	property color dialogsRippleBg: "#43474d"
	property color dialogsRippleBgActive: "#12a798"
	property color dialogsForwardBg: dialogsBgActive
	property color dialogsForwardFg: dialogsNameFgActive
	property color searchedBarBg: "#3a4047"
	property color searchedBarFg: "#a8a8a8"
	property color topBarBg: "#282e33"
	property color emojiPanBg: windowBg
	property color emojiPanCategories: "#20262b"
	property color emojiPanHeaderFg: "#90949a"
	property color emojiPanHeaderBg: "#fffffff2"
	property color stickerPanDeleteBg: "#000000cc"
	property color stickerPanDeleteFg: windowFgActive
	property color stickerPreviewBg: "#000000b0"
	property color historyTextInFg: windowFg
	property color historyTextInFgSelected: "#ffffff"
	property color historyTextOutFg: "#e4ecf2"
	property color historyTextOutFgSelected: "#ffffff"
	property color historyLinkInFg: "#37e1cb"
	property color historyLinkInFgSelected: "#a7fff4"
	property color historyLinkOutFg: "#37e1cb"
	property color historyLinkOutFgSelected: "#a7fff4"
	property color historyFileNameInFg: historyTextInFg
	property color historyFileNameInFgSelected: "#ffffff"
	property color historyFileNameOutFg: historyTextOutFg
	property color historyFileNameOutFgSelected: "#ffffff"
	property color historyOutIconFg: "#40e6c5"
	property color historyOutIconFgSelected: "#ffffff"
	property color historyIconFgInverted: "#40e6c5"
	property color historySendingOutIconFg: "#9eface"
	property color historySendingInIconFg: "#76838b"
	property color historySendingInvertedIconFg: "#ffffffc8"
	property color historyCallArrowInFg: "#26c2ad"
	property color historyCallArrowInFgSelected: "#ffffff"
	property color historyCallArrowMissedInFg: callArrowMissedFg
	property color historyCallArrowMissedInFgSelected: "#ffffff"
	property color historyCallArrowOutFg: "#ffffff"
	property color historyCallArrowOutFgSelected: "#ffffff"
	property color historyUnreadBarBg: "#33393f"
	property color historyUnreadBarBorder: shadowFg
	property color historyUnreadBarFg: "#3cd3bf"
	property color historyForwardChooseBg: "#0000004c"
	property color historyForwardChooseFg: windowFgActive
	property color historyPeer1NameFg: "#ec7577"
	property color historyPeer1NameFgSelected: "#ffffff"
	property color historyPeer1UserpicBg: "#e17076"
	property color historyPeer2NameFg: "#86d67f"
	property color historyPeer2NameFgSelected: "#ffffff"
	property color historyPeer2UserpicBg: "#7bc862"
	property color historyPeer3NameFg: "#e4c054"
	property color historyPeer3NameFgSelected: "#ffffff"
	property color historyPeer3UserpicBg: "#ccad4f"
	property color historyPeer4NameFg: "#68c7f3"
	property color historyPeer4NameFgSelected: "#ffffff"
	property color historyPeer4UserpicBg: "#65aadd"
	property color historyPeer5NameFg: "#b383f3"
	property color historyPeer5NameFgSelected: "#ffffff"
	property color historyPeer5UserpicBg: "#a695e7"
	property color historyPeer6NameFg: "#e16794"
	property color historyPeer6NameFgSelected: "#ffffff"
	property color historyPeer6UserpicBg: "#ee7aae"
	property color historyPeer7NameFg: "#57c9e0"
	property color historyPeer7NameFgSelected: "#ffffff"
	property color historyPeer7UserpicBg: "#6ec9cb"
	property color historyPeer8NameFg: "#efb05d"
	property color historyPeer8NameFgSelected: "#ffffff"
	property color historyPeer8UserpicBg: "#eda86c"
	property color historyPeerUserpicFg: windowFgActive
	property color historyScrollBarBg: "#8989897a"
	property color historyScrollBarBgOver: "#6b6b6bbc"
	property color historyScrollBg: "#5f5f5f4c"
	property color historyScrollBgOver: "#6262626b"
	property color msgInBg: "#33393f"
	property color msgInBgSelected: "#009687"
	property color msgOutBg: "#2a2f33"
	property color msgOutBgSelected: "#009687"
	property color msgSelectOverlay: "#35d4bf4c"
	property color msgStickerOverlay: "#35d4bf7f"
	property color msgInServiceFg: windowActiveTextFg
	property color msgInServiceFgSelected: "#ffffff"
	property color msgOutServiceFg: "#60e5cb"
	property color msgOutServiceFgSelected: "#ffffff"
	property color msgInShadow: "#748ea200"
	property color msgInShadowSelected: "#538ebb00"
	property color msgOutShadow: "#00000000"
	property color msgOutShadowSelected: "#37a78d00"
	property color msgInDateFg: "#828d94"
	property color msgInDateFgSelected: "#ffffff"
	property color msgOutDateFg: "#737f87"
	property color msgOutDateFgSelected: "#ffffff"
	property color msgServiceFg: windowFgActive
	property color msgServiceBg: "#363c43c8"
	property color msgServiceBgSelected: "#009687"
	property color msgInReplyBarColor: "#32ceb9"
	property color msgInReplyBarSelColor: "#ffffff"
	property color msgOutReplyBarColor: "#32ceb9"
	property color msgOutReplyBarSelColor: "#ffffff"
	property color msgImgReplyBarColor: msgServiceFg
	property color msgInMonoFg: "#5aaba0"
	property color msgOutMonoFg: "#c2f2ec"
	property color msgInMonoFgSelected: "#a7fff4"
	property color msgOutMonoFgSelected: "#c9fff8"
	property color msgDateImgFg: msgServiceFg
	property color msgDateImgBg: "#00000054"
	property color msgDateImgBgOver: "#00000074"
	property color msgDateImgBgSelected: "#1c706587"
	property color msgFileThumbLinkInFg: lightButtonFg
	property color msgFileThumbLinkInFgSelected: lightButtonFgOver
	property color msgFileThumbLinkOutFg: "#60e5cb"
	property color msgFileThumbLinkOutFgSelected: "#ffffff"
	property color msgFileInBg: "#50d4c3"
	property color msgFileInBgOver: "#48cfbd"
	property color msgFileInBgSelected: "#ffffff"
	property color msgFileOutBg: "#11bfab"
	property color msgFileOutBgOver: "#ffffff"
	property color msgFileOutBgSelected: "#ffffff"
	property color msgFile1Bg: "#3fbbab"
	property color msgFile1BgDark: "#269f8f"
	property color msgFile1BgOver: "#52c4b5"
	property color msgFile1BgSelected: "#ffffff"
	property color msgFile2Bg: "#8ef5e8"
	property color msgFile2BgDark: "#7ef7e7"
	property color msgFile2BgOver: "#8df7e9"
	property color msgFile2BgSelected: "#ffffff"
	property color msgFile3Bg: "#e47272"
	property color msgFile3BgDark: "#cd5b5e"
	property color msgFile3BgOver: "#c35154"
	property color msgFile3BgSelected: "#9f6a82"
	property color msgFile4Bg: "#efc274"
	property color msgFile4BgDark: "#e6a561"
	property color msgFile4BgOver: "#dc9c5a"
	property color msgFile4BgSelected: "#b19d84"
	property color historyFileInIconFg: "#33393f"
	property color historyFileInIconFgSelected: "#009687"
	property color historyFileInRadialFg: "#33393f"
	property color historyFileInRadialFgSelected: historyFileInIconFgSelected
	property color historyFileOutIconFg: "#33393f"
	property color historyFileOutIconFgSelected: "#009687"
	property color historyFileOutRadialFg: historyFileOutIconFg
	property color historyFileOutRadialFgSelected: "#009687"
	property color historyFileThumbIconFg: "#efefef"
	property color historyFileThumbIconFgSelected: "#ffffff"
	property color historyFileThumbRadialFg: historyFileThumbIconFg
	property color historyFileThumbRadialFgSelected: "#ffffff"
	property color historyVideoMessageProgressFg: historyFileThumbIconFg
	property color msgWaveformInActive: windowBgActive
	property color msgWaveformInActiveSelected: "#ffffff"
	property color msgWaveformInInactive: "#5d6b76"
	property color msgWaveformInInactiveSelected: "#41d1c0"
	property color msgWaveformOutActive: "#11bfab"
	property color msgWaveformOutActiveSelected: "#ffffff"
	property color msgWaveformOutInactive: "#596874"
	property color msgWaveformOutInactiveSelected: "#41d1c0"
	property color msgBotKbOverBgAdd: "#ffffff14"
	property color msgBotKbIconFg: msgServiceFg
	property color msgBotKbRippleBg: "#9e9d9d10"
	property color mediaInFg: msgInDateFg
	property color mediaInFgSelected: msgInDateFgSelected
	property color mediaOutFg: msgOutDateFg
	property color mediaOutFgSelected: msgOutDateFgSelected
	property color youtubePlayIconBg: "#e83131c8"
	property color youtubePlayIconFg: windowFgActive
	property color videoPlayIconBg: "#0000007f"
	property color videoPlayIconFg: "#ffffff"
	property color toastBg: "#000000b2"
	property color toastFg: windowFgActive
	property color reportSpamBg: "#363c42"
	property color reportSpamFg: windowFg
	property color historyToDownBg: "#434d57"
	property color historyToDownBgOver: "#515b65"
	property color historyToDownBgRipple: "#636d77"
	property color historyToDownFg: "#adb4ba"
	property color historyToDownFgOver: menuIconFgOver
	property color historyToDownShadow: "#00000040"
	property color historyComposeAreaBg: "#282e33"
	property color historyComposeAreaFg: historyTextInFg
	property color historyComposeAreaFgService: msgInDateFg
	property color historyComposeIconFg: menuIconFg
	property color historyComposeIconFgOver: menuIconFgOver
	property color historySendIconFg: windowBgActive
	property color historySendIconFgOver: windowBgActive
	property color historyPinnedBg: historyComposeAreaBg
	property color historyReplyBg: historyComposeAreaBg
	property color historyReplyIconFg: windowBgActive
	property color historyReplyCancelFg: cancelIconFg
	property color historyReplyCancelFgOver: cancelIconFgOver
	property color historyComposeButtonBg: historyComposeAreaBg
	property color historyComposeButtonBgOver: "#31363c"
	property color historyComposeButtonBgRipple: "#272b2f"
	property color overviewCheckBg: "#00000040"
	property color overviewCheckFg: "#ffffff"
	property color overviewCheckFgActive: "#ffffff"
	property color overviewPhotoSelectOverlay: "#40ace333"
	property color profileStatusFgOver: "#9c9c9c"
	property color profileVerifiedCheckBg: windowBgActive
	property color profileVerifiedCheckFg: "#ffffff"
	property color profileAdminStartFg: windowBgActive
	property color notificationsBoxMonitorFg: windowFg
    property color notificationsBoxScreenBg: dialogsBgActive
	property color notificationSampleUserpicFg: windowBgActive
	property color notificationSampleCloseFg: "#d7d7d7"
	property color notificationSampleTextFg: "#d7d7d7"
	property color notificationSampleNameFg: "#939393"
	property color changePhoneSimcardFrom: notificationSampleTextFg
	property color changePhoneSimcardTo: notificationSampleNameFg
	property color mainMenuBg: windowBg
	property color mainMenuCoverBg: "#009687"
	property color mainMenuCoverFg: windowFgActive
	property color mainMenuCloudFg: activeButtonFg
	property color mainMenuCloudBg: "#0e837f"
	property color mediaPlayerBg: windowBg
	property color mediaPlayerActiveFg: windowBgActive
	property color mediaPlayerInactiveFg: sliderBgInactive
	property color mediaPlayerDisabledFg: "#9dd1ef"
	property color mediaviewFileBg: windowBg
	property color mediaviewFileNameFg: windowFg
	property color mediaviewFileSizeFg: windowSubTextFg
	property color mediaviewFileRedCornerFg: "#d55959"
	property color mediaviewFileYellowCornerFg: "#e8a659"
	property color mediaviewFileGreenCornerFg: "#49a957"
	property color mediaviewFileBlueCornerFg: "#599dcf"
	property color mediaviewFileExtFg: activeButtonFg
	property color mediaviewMenuBg: "#383838"
	property color mediaviewMenuBgOver: "#505050"
	property color mediaviewMenuBgRipple: "#676767"
	property color mediaviewMenuFg: windowFgActive
	property color mediaviewBg: "#222222eb"
	property color mediaviewVideoBg: imageBg
	property color mediaviewControlBg: "#0000003c"
	property color mediaviewControlFg: windowFgActive
	property color mediaviewCaptionBg: "#11111180"
	property color mediaviewCaptionFg: mediaviewControlFg
	property color mediaviewTextLinkFg: "#66f7e4"
	property color mediaviewSaveMsgBg: toastBg
	property color mediaviewSaveMsgFg: toastFg
	property color mediaviewPlaybackActive: "#c7c7c7"
	property color mediaviewPlaybackInactive: "#252525"
	property color mediaviewPlaybackActiveOver: "#ffffff"
	property color mediaviewPlaybackInactiveOver: "#474747"
	property color mediaviewPlaybackProgressFg: "#ffffffc7"
	property color mediaviewPlaybackIconFg: mediaviewPlaybackActive
	property color mediaviewPlaybackIconFgOver: mediaviewPlaybackActiveOver
	property color mediaviewTransparentBg: "#ffffff"
	property color mediaviewTransparentFg: "#cccccc"
	property color notificationBg: windowBg
	property color callBg: "#26282cf2"
	property color callNameFg: "#ffffff"
	property color callFingerprintBg: "#00000066"
	property color callStatusFg: "#aaabac"
	property color callIconFg: "#ffffff"
	property color callAnswerBg: "#5ad1c1"
	property color callAnswerRipple: "#42c2b1"
	property color callAnswerBgOuter: "#3febc926"
	property color callHangupBg: "#d75a5a"
	property color callHangupRipple: "#c04646"
	property color callCancelBg: "#ffffff"
	property color callCancelFg: "#777777"
	property color callCancelRipple: "#f1f1f1"
	property color callMuteRipple: "#ffffff12"
	property color callBarBg: dialogsBgActive
	property color callBarMuteRipple: dialogsRippleBgActive
	property color callBarBgMuted: "#8f8f8f"
	property color callBarUnmuteRipple: "#7f7f7f"
	property color callBarFg: dialogsNameFgActive
	property color importantTooltipBg: toastBg
	property color importantTooltipFg: toastFg
	property color importantTooltipFgLink: "#65fce8"
	property color filterInputActiveBg: "#3d444b"
	property color botKbBg: "#3d444b"
	property color botKbDownBg: "#494f55"
	property color emojiIconFg: "#6c7278"
	property color emojiIconFgActive: "#36cdb9"
	property color overviewCheckBorder: "#e4eaef"
	property color sideBarBg: "#18191d"
	property color sideBarBgActive: "#282e33"
	property color sideBarBgRipple: "#22272b"
	property color sideBarTextFg: "#8d939e"
	property color sideBarTextFgActive: "#24c9b9"
	property color sideBarIconFg: "#8d939e"
	property color sideBarIconFgActive: "#25dbca"
	property color sideBarBadgeBg: "#25dbca"
	property color sideBarBadgeBgMuted: "#8d939e"

    property string chatBackgroundImg: "qrc:/style/themes/nightGreen/background.png"
}

